trigger:
- master

variables:
- group: production

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - task: CopyFiles@2
      displayName: 'Copy files to build directory'
      inputs:
        contents: |
          dist/**
          views/**
          node_modules/**
        targetFolder: '$(Pipeline.Workspace)/build'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/build'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Deploy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
    - deployment: VMDeploy
      displayName: 'Deploy to droplet'
      environment:
        name: 'production'
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: pm2 stop Home

              - task: CopyFiles@2
                inputs:
                  sourceFolder: '$(Pipeline.Workspace)/drop'
                  contents: '**'
                  targetFolder: '$(deploy_path)'
                  cleanTargetFolder: true

              - task: Bash@3
                inputs:
                  filePath: '$(deploy_script_path)'

              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: pm2 start Home